name: humansf
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pip:
    - pip
    - ray[tune]
    - ipdb
    - matplotlib
    - wandb
    - chex==0.1.6




# mamba create --name humansf python=3.9 pip wheel -y
# mamba env update --file humansf.yaml --prune
# mamba remove --name omodel --all -y