name: neurorl
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pip:
    - ray[tune]==2.7.1
    - matplotlib==3.8.1
    - wandb
    - ipdb
    - mctx==0.0.5
    - minigrid




# mamba create --name neurorl python=3.9 pip wheel -y
# mamba env update --file neurorl.yaml --prune
# mamba remove --name neurorl --all -y